### ISSUE TITLE
Strong assumptions about form of distributions in TestUtils

### ISSUE THREAD

**Issue by willtebbutt** [invenia/Models.jl#18]
The `Models.TestUtils` tests currently assume that single-output regressors return vectors of `Normal` distributions, and that multi-output regressors return `Vector`s of `MvNormal`s. See [here](https://github.com/invenia/Models.jl/blob/9fa0caa695f621baeb6953fd354413b54b85339a/src/test_utils.jl#L161) and [here](https://github.com/invenia/Models.jl/blob/9fa0caa695f621baeb6953fd354413b54b85339a/src/test_utils.jl#L171) resp.

@glennmoy @nickrobinson251 why are we doing this? It seems overly-restrictive.

**Comment by nickrobinson251** [comment]
hm. seem wrong
I don't think we need to test for `Real` eltype either

should probably just test for Univariate and Multivariate distributions?

but @glennmoy may know better

**Comment by glennmoy** [comment]
>It seems overly-restrictive

Yeah I think is just a legacy of when it lived in our internal code base.
I don't think there was a conscious decision to restrict them so much - at least going by the initial review there was no comment made about it.

I think it's reasonable to replace with `<:Univariate` and `<:Multivariate` (I assume that's what you mean?) and not worry about the eltype as @nickrobinson251 says.
