### ISSUE TITLE
Add submodels()

### ISSUE THREAD

**Issue by oxinabox** [invenia/Models.jl#3]
This is a feature in our main internal models package,  
for a multistage/composed model, `submodels(model)` returns the trained model for each of the components.
If it is a concrete model, then it returns a empty tuple.

Similar for tempates. `submodels(template)` returns a template for each component, or an empty tuple if  template is not for a  compositional model

`submodels` should be defined here and overloaded in packages implementing models.

**Comment by nickrobinson251** [comment]
closed via #10
